### ISSUE TITLE
Unable to install "Extension Pack for Java" extensions

### ISSUE THREAD

**Issue by saikeerthan-14** [microsoft/vscode-java-pack#1137]
Error:
`2023-01-16 11:30:27.261 [error] Error: XHR failed,XHR failed
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88554
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88540)
    at Z.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79894)
    at async Z.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77428)
    at async Z.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73871)
2023-01-16 11:30:27.284 [error] XHR failed,XHR failed: Error: XHR failed,XHR failed
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88554
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88540)
    at Z.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79894)
    at async Z.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77428)
    at async Z.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73871)
`

**Comment by nickzhums** [comment]
Could you provide the detailed steps to reproduce this error?
