### ISSUE TITLE
Question: Would `Error: Can't resolve 'process/browser'` prevent building?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-java-pack#1153]
I saw this error and was wondering if it would prevent me from seeing any changes I made.

<details>
<summary>Error message image</summary>
<br>

![image](https://user-images.githubusercontent.com/43425812/218282452-8eefa082-6c1c-4ff1-a838-99996562f49a.png)
</details>

<details>
<summary>Long error message text</summary>
<br>

```
ERROR in ./node_modules/immer/dist/immer.esm.mjs 1:110-117
  Module not found: Error: Can't resolve 'process/browser' in '/home/hamir/repositories/vscode-java-pack/node_modules/immer/dist'
  Did you mean 'browser.js'?
  BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  resolve 'process/browser' in '/home/hamir/repositories/vscode-java-pack/node_modules/immer/dist'
    Parsed request is a module
    using description file: /home/hamir/repositories/vscode-java-pack/node_modules/immer/package.json (relative path: ./dist)
      Field 'browser' doesn't contain a valid alias configuration
      resolve as module
        /home/hamir/repositories/vscode-java-pack/node_modules/immer/dist/node_modules doesn't exist or is not a directory
        /home/hamir/repositories/vscode-java-pack/node_modules/immer/node_modules doesn't exist or is not a directory
        /home/hamir/repositories/vscode-java-pack/node_modules/node_modules doesn't exist or is not a directory
        looking for modules in /home/hamir/repositories/vscode-java-pack/node_modules
          existing directory /home/hamir/repositories/vscode-java-pack/node_modules/process
            using description file: /home/hamir/repositories/vscode-java-pack/node_modules/process/package.json (relative path: .)
              using description file: /home/hamir/repositories/vscode-java-pack/node_modules/process/package.json (relative path: ./browser)
                Field 'browser' doesn't contain a valid alias configuration
                /home/hamir/repositories/vscode-java-pack/node_modules/process/browser doesn't exist
        /home/hamir/repositories/node_modules doesn't exist or is not a directory
        /home/hamir/node_modules doesn't exist or is not a directory
        /home/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
   @ ./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js 91:0-34 93:0-104 96:0-41 109:53-60 109:70-77 145:0-53 204:11-22 204:30-45 523:0-91 599:20-28 607:26-38 618:27-43 731:0-62 751:12-20 756:19-35 1778:0-9 1779:0-686 1779:0-686 1779:0-686 1779:0-686 1779:0-686
   @ ./src/formatter-settings/assets/app/store.ts 8:18-45
   @ ./src/formatter-settings/assets/index.tsx 32:32-54

  ERROR in ./node_modules/immer/dist/immer.esm.mjs
  Cannot read properties of undefined (reading 'module')
  TypeError: Cannot read properties of undefined (reading 'module')
      at ProvidedDependencyTemplate.apply (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/dependencies/ProvidedDependency.js:122:61)
      at JavascriptGenerator.sourceDependency (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
      at JavascriptGenerator.sourceModule (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
      at JavascriptGenerator.generate (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
      at NormalModule.codeGeneration (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/NormalModule.js:1204:22)
      at /home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/Compilation.js:3326:22
      at /home/hamir/repositories/vscode-java-pack/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
      at /home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/Cache.js:93:5
      at Hook.eval [as callAsync] (eval at create (/home/hamir/repositories/vscode-java-pack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Cache.get (/home/hamir/repositories/vscode-java-pack/node_modules/webpack/lib/Cache.js:75:18)
   @ ./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js 91:0-34 93:0-104 96:0-41 109:53-60 109:70-77 145:0-53 204:11-22 204:30-45 523:0-91 599:20-28 607:26-38 618:27-43 731:0-62 751:12-20 756:19-35 1778:0-9 1779:0-686 1779:0-686 1779:0-686 1779:0-686 1779:0-686
   @ ./src/formatter-settings/assets/app/store.ts 8:18-45
   @ ./src/formatter-settings/assets/index.tsx 32:32-54

  assets (webpack 5.74.0) compiled with 2 errors in 21079 ms
```
</details>

**Comment by hamirmahal** [comment]
It doesn't seem like it's relevant, but I'm using WSL2 on a Windows 10 machine with an i7-7700K.

**Comment by hamirmahal** [comment]
It's probably not relevant, but I'm using WSL2 on a Windows 10 machine with an i7-7700K.

**Comment by Eskibear** [comment]
I've met this before. Try totally removing `node_modules` folder, and clean npm cache.
