### ISSUE TITLE
Server Language Support for Java call timeout.

### ISSUE THREAD

**Issue by alexanderloong** [microsoft/vscode-java-pack#1246]
Type: <b>Bug</b>

When enable Pack for Java then Language Support for Java call server timeout.

Extension version: 0.25.14
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.63GB (12.35GB free)|
|Process Argv|--folder-uri file:///d%3A/VNPAY/Project/IndovinaVietnam/source_IVB --crash-reporter-id 6ed9de60-dd67-4364-a1cb-6869da025e9e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by testforstephen** [comment]
Please provide more details about the issue. What error message do you see?

**Comment by alexanderloong** [comment]
> Please provide more details about the issue. What error message do you see?

![image](https://github.com/microsoft/vscode-java-pack/assets/51206070/0bd699f2-0c76-4a81-a8ac-57d06b395ef4)
When i enable Java Pack For Java and Spring boot pack.

![image](https://github.com/microsoft/vscode-java-pack/assets/51206070/24861394-f233-4f90-8fe2-c9905f2e2c2f)
And when i disable Java Pack and Spring Boot Pack that so Ok.

**Comment by testforstephen** [comment]
Hmm, I don't see that uncaught error when I enabled java pack and Java language support extension in my machine. Can you open VS Code "**OUTPUT -> Extension Host**" to check any more info about that uncaught error?

**Comment by alexanderloong** [comment]
> Hmm, I don't see that uncaught error when I enabled java pack and Java language support extension in my machine. Can you open VS Code "**OUTPUT -> Extension Host**" to check any more info about that uncaught error?

How can i do it?

**Comment by alexanderloong** [comment]
> Hmm, I don't see that uncaught error when I enabled java pack and Java language support extension in my machine. Can you open VS Code "**OUTPUT -> Extension Host**" to check any more info about that uncaught error?

`2023-09-28 14:05:04.190 [warning] [vscjava.vscode-gradle] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
2023-09-28 14:05:13.728 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-09-28 14:05:28.309 [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
2023-09-28 14:05:33.071 [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
2023-09-28 14:05:33.111 [info] ExtensionService#_doActivateExtension vscjava.vscode-java-test, startup: false, activationEvent: 'onLanguage:java'
2023-09-28 14:05:33.149 [error] Unable to acquire a lock to modify the recommendation model.
2023-09-28 14:05:50.178 [info] Eager extensions activated
2023-09-28 14:05:56.893 [error] [redhat.java] provider FAILED
2023-09-28 14:05:56.896 [error] Error: The request (id: 13, method: 'textDocument/hover') has been cancelled
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086579
	at ie (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086873)
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081657
	at Immediate.<anonymous> (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081677)
	at process.processImmediate (node:internal/timers:476:21)
2023-09-28 14:05:57.734 [error] Error: Stopping the server timed out
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1143456
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processTimers (node:internal/timers:509:9)
2023-09-28 14:06:32.459 [error] [redhat.java] provider FAILED
2023-09-28 14:06:32.459 [error] Error: The request (id: 38, method: 'textDocument/hover') has been cancelled
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086579
	at ie (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086873)
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081657
	at Immediate.<anonymous> (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081677)
	at process.processImmediate (node:internal/timers:476:21)
2023-09-28 14:06:42.402 [error] Error: ENOENT: no such file or directory, lstat 'd:\VNPAY\Project\IndovinaVietnam\source_IVB\src\main\java\vn\vnpay\bussiness\BussinessManager.java.git'
2023-09-28 14:07:07.503 [error] [redhat.java] provider FAILED
2023-09-28 14:07:07.503 [error] Error: The request (id: 41, method: 'textDocument/hover') has been cancelled
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086579
	at ie (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086873)
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081657
	at Immediate.<anonymous> (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081677)
	at process.processImmediate (node:internal/timers:476:21)
2023-09-28 14:07:07.504 [error] [redhat.java] provider FAILED
2023-09-28 14:07:07.504 [error] Error: The request (id: 43, method: 'textDocument/hover') has been cancelled
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086579
	at ie (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1086873)
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081657
	at Immediate.<anonymous> (c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1081677)
	at process.processImmediate (node:internal/timers:476:21)
`
We can see errors.

**Comment by testforstephen** [comment]
Anything related with the error "Stopping the server timed out"?

**Comment by alexanderloong** [comment]
> Anything related with the error "Stopping the server timed out"?

2023-09-28 14:16:36.323 [error] Error: Stopping the server timed out
	at c:\Users\thaond\.vscode\extensions\redhat.java-1.22.1-win32-x64\dist\extension.js:2:1143456
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processTimers (node:internal/timers:509:9)

This is error

**Comment by testforstephen** [comment]
See https://github.com/microsoft/vscode-languageserver-node/blob/4b77bb4d2e47dbfeeed6c263c28054eced60e030/client/src/common/client.ts#L1408

This seems to be a random error that is not related to the java pack. It should not affect any feature. If there is any feature breaking, feel free to let us know.

**Comment by alexanderloong** [comment]
> See https://github.com/microsoft/vscode-languageserver-node/blob/4b77bb4d2e47dbfeeed6c263c28054eced60e030/client/src/common/client.ts#L1408
> 
> This seems to be a random error that is not related to the java pack. It should not affect any feature. If there is any feature breaking, feel free to let us know.

![image](https://github.com/microsoft/vscode-java-pack/assets/51206070/9650f6a5-6e10-41bf-a3e6-8e38586ba357)
Because if have this error, i meet problem when point to method. It so slowly.

**Comment by testforstephen** [comment]
Could you share the logs from **F1 -> Java: Open All Log Files**? if possible, share a minimum sample project to reproduce the issue? thanks.

**Comment by alexanderloong** [comment]
[log.txt](https://github.com/microsoft/vscode-java-pack/files/12747925/log.txt)


> Could you share the logs from **F1 -> Java: Open All Log Files**? if possible, share a minimum sample project to reproduce the issue? thanks.
