### ISSUE TITLE
Quick actions in problem window doesn't work 

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-java-pack#1284]
**Environment:**

- VS Code Version: Github Codespace
- Extension Version: 1.27.0
- JDK Type & Version: java 21
- OS Type & Version: windows

**Step to Reproduce:**
1. Clone and open https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/eclipse/simple-app
2. Disable 'PasteAs' in settings > Open a java file and paste 'File f = new File("demo.txt");'
3. Go to problem window > Click on error message, the line of error will be highlighted > Then click on light blub, all actions here don't work

**Expected Behavior:**
Quick actions in problem should work well.

**Actual Behavior:**
![image](https://github.com/microsoft/vscode-java-pack/assets/31497677/dfffc96c-4ba4-45bb-8636-cbe8f4faca2a)

**Comment by testforstephen** [comment]
```
SEVERE: Internal error: java.lang.IllegalStateException: Invalid codeAction proposal
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Invalid codeAction proposal
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Invalid codeAction proposal
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionResolveHandler.resolve(CodeActionResolveHandler.java:44)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$15(JDTLanguageServer.java:793)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	... 3 more
```
