### ISSUE TITLE
Java Compiler Bug: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Liipski** [microsoft/vscode-java-pack#282]
Issue Type: <b>Bug</b>

Java compiler returns "Exception in thread "main" java.lang.NoSuchMethodError: 'int Vehicle.range()'
        at RetMeth.main(RetMeth.java:28)" 
when compiling in Command Line or IntelliJ returns desired output of the program.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.14
java|red|0.54.2
glassit|s-n|0.1.6
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1

(3 theme extensions excluded)

</details>

<details><summary>Full code</summary>

```
class Vehicle{
int passengers;
int fuelcap;
   double lkm;
   //zwraca zasieg
   int range(){
      return (int) (fuelcap / lkm * 100);
   }
}
class RetMeth{
   public static void main(String[] args) {
      Vehicle minivan = new Vehicle();
      Vehicle sportscar = new Vehicle();

      minivan.passengers = 7;
      minivan.fuelcap = 65;
      minivan.lkm = 9.1;

      sportscar.passengers = 2;
      sportscar.fuelcap = 55;
      sportscar.lkm = 12.5;

      int range1 = minivan.range(); //line 28
      int range2 = sportscar.range(); //line 29

      System.out.print("Minivan przewozi " + minivan.passengers + " osób na odległość do " + range1 + " kilometrów");

      System.out.print("Auto sportowe przewozi " + sportscar.passengers + " osób na odległość do " + range2 + " kilometrów");
   }
}

```
</details>

**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**
the bug seems to occur at line 28 and 29 of my code that goes:
 ```
int range1 = minivan.
int range2 = sportscar.range();
```
**Expected Behavior:**
expected output: "Minivan przewozi 7 osób na odległość do 714 kilometrówAuto sportowe przewozi 2 osób na odległość do 440 kilometrów"
**Actual Behavior:**
Exception in thread "main" java.lang.NoSuchMethodError: 'int Vehicle.range()'
        at RetMeth.main(RetMeth.java:28)
**Related Issues:**

**Comment by akaroml** [comment]
@liipski thanks for reaching out.

Looks like a LS issue. @testforstephen, could you please take a look?

**Comment by chagong** [comment]
<img width="1741" height="1277" alt="Image" src="https://github.com/user-attachments/assets/f9200e16-678a-4e66-8668-64b776c24399" />
