### ISSUE TITLE
Add Lombok Annotations to the Java extension pack

### ISSUE THREAD

**Issue by dupinder** [microsoft/vscode-java-pack#399]
## Suggestion

I Love VSCode, so I want to use this for Java too. for that I added required plugins, extensions packs, and did everything what else VSCode suggested, but no success. After a long post related to
 `Java crashed 5 times in last 3 min`. I found a way out to run java in vscode. Install `Lombok Annotations`

* Link
https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok

## Use Cases

* Peoples problems will be resolved easily
* Dev will love more VS Code
* Will be a preferance for java dev if there problem is resolved in one click

## problem referances 

https://github.com/redhat-developer/vscode-java/issues/743

https://github.com/redhat-developer/vscode-java/issues/305

**Comment by dupinder** [comment]
If someone please give me a idea, I can fix this issue :)

**Comment by akaroml** [comment]
@dupinder thanks for reaching out to us.

From the description you provided, I guess you should be using Lombok in your project, otherwise, the Lombok extension should not be able to fix the crash problem.

To identify the root cause, I would suggest that you share the log files with us. You can find the logs by running command "Java: Open all log files".

Furthermore, your project definition (pom.xml contents) would also be helpful for us to understand the scenarios.

**Comment by dupinder** [comment]
@akaroml I think i need to uninstall Lombok and then again try to run java project in VS that might give me logs to share with you

**Comment by dupinder** [comment]
I did it, Uninstall lombok and created one java file and boom 


`!SESSION 2020-07-08 14:19:37.520 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -data c:\Users\DupinderDhiman\AppData\Roaming\Code\User\workspaceStorage\4e625fc2a7de9452fc01413556afae12\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.111
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.398
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.463
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.482
!MESSAGE Initializing Java Language Server 0.58.0.202007061829

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.615
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.617
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.provideSemanticTokens, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.project.getSemanticTokensLegend, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.619
!MESSAGE Static Commands: [sts.java.addClasspathListener, sts.java.removeClasspathListener]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.620
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.635
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.638
!MESSAGE Non-Static Commands: [sts.java.javadoc]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.639
!MESSAGE Static Commands: [sts.java.type]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.640
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.641
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.645
!MESSAGE Non-Static Commands: [sts.java.javadocHoverLink]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.648
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.650
!MESSAGE Non-Static Commands: [sts.java.location]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.651
!MESSAGE Static Commands: [sts.java.search.packages, sts.java.search.types]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.652
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.653
!MESSAGE Static Commands: [sts.java.hierarchy.supertypes, sts.java.hierarchy.subtypes]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.655
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.656
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.656
!MESSAGE Non-Static Commands: [sts.java.code.completions]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.658
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.658
!MESSAGE Non-Static Commands: [java.intellicode.completion, java.intellicode.completion.resolve, java.intellicode.enable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.659
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.661
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.fetchPlatformSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection, vscode.java.resolveJavaExecutable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.663
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.664
!MESSAGE Non-Static Commands: [java.project.refreshLib, java.project.list, java.getPackageData, java.resolvePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.665
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.668
!MESSAGE Non-Static Commands: [vscode.java.test.search.codelens, vscode.java.test.search.items.all, vscode.java.test.search.location, vscode.java.test.search.items, vscode.java.test.get.testpath, vscode.java.test.junit.argument]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.670
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.673
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.708
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:52.793
!MESSAGE Creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:53.042
!MESSAGE Finished creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.296
!MESSAGE Try to create an invisible project for the workspace E:/Projects/stackoverflow/javaExample/SOjavaExample

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.299
!MESSAGE Creating the Java project SOjavaExample_416796a5

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.486
!MESSAGE Finished creating the Java project SOjavaExample_416796a5

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.553
!MESSAGE Successfully created a workspace invisible project SOjavaExample_416796a5

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.556
!MESSAGE Workspace initialized in 2878ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.605
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.657
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.788
!MESSAGE >> New configuration: {java={home=E:\Open_JDK\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:"c:\Users\DupinderDhiman\.vscode\extensions\gabrielbb.vscode-lombok-1.0.1\server\lombok.jar"}}, errors={incompleteClasspath={severity=warning}}, configuration={checkProjectSettingsExclusions=true, updateBuildConfiguration=interactive, maven={userSettings=null}, runtimes=[]}, trace={server=off}, import={maven={enabled=true}, gradle={enabled=true, wrapper={enabled=true}, offline={enabled=false}, version=null, arguments=null, jvmArguments=null, home=null, user={home=null}}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, maven={downloadSources=false, updateSnapshots=false}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, project={referencedLibraries=[lib/**/*.jar], importOnFirstTimeStartup=interactive, importHint=true}, contentProvider={preferred=}, autobuild={enabled=false}, maxConcurrentBuilds=1.0, completion={maxResults=0.0, enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*], importOrder=[java, javax, com, org]}, foldingRange={enabled=true}, progressReports={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}}, selectionRange={enabled=true}, showBuildStatusOnStart={enabled=false}, server={launchMode=Hybrid}, sources={organizeImports={starThreshold=99.0, staticStarThreshold=99.0}}, semanticHighlighting={enabled=true}, requirements={JDK11Warning=true}, refactor={renameFromFileExplorer=prompt}, imports={gradle={wrapper={checksums=[]}}}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=false, showQualifiedNames=false, showLogicalStructure=true, showToString=true, maxStringLength=0.0, numericPrecision=0.0, hotCodeReplace=manual, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true, console=integratedTerminal}}, dependency={showMembers=false, syncWithFolderExplorer=true, autoRefresh=true, refreshDelay=2000.0, packagePresentation=flat}, help={firstView=gettingStarted}, test={report={showAfterExecution=onFailure, position=sideView}, editor={enableShortcuts=true}, log={level=info}, message={hintForDeprecatedConfig=true, hintForSetingDefaultConfig=true}, defaultConfig=, config={}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.791
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:55.881
!MESSAGE >> Updating classpath for project SOjavaExample_416796a5

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.127
!MESSAGE >> workspace/executeCommand java.intellicode.enable

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.137
!MESSAGE >> workspace/executeCommand java.project.isTestFile

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.150
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.153
!MESSAGE Reconciled 0. Took 4 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.193
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.195
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:56.209
!MESSAGE >> workspace/executeCommand java.project.getSettings

!ENTRY java-debug 1 0 2020-07-08 14:19:56.289
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.404
!MESSAGE begin problem for /B.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.405
!MESSAGE 0 problems reported for /B.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.425
!MESSAGE Validated 1. Took 1216 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.477
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.508
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.583
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.587
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:19:57.590
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:01.691
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:01.694
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.113
!MESSAGE >> workspace/executeCommand java.project.getClasspaths

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.256
!MESSAGE >> workspace/executeCommand vscode.java.test.get.testpath

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.387
!MESSAGE >> workspace/executeCommand java.project.getAll

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.514
!MESSAGE >> workspace/executeCommand java.project.getSemanticTokensLegend

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.594
!MESSAGE >> workspace/executeCommand java.project.getSettings

!ENTRY org.eclipse.jdt.ls.core 4 2 2020-07-08 14:20:02.673
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 1
org.eclipse.core.runtime.CoreException: Given URI does not belong to any Java project.
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getJavaProjectFromUri(ProjectCommand.java:257)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getProjectSettings(ProjectCommand.java:82)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:65)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:495)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
!SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2020-07-08 14:20:02.675
!MESSAGE Given URI does not belong to any Java project.
!SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2020-07-08 14:20:02.675
!MESSAGE Given URI does not belong to any Java project.

!ENTRY org.eclipse.jdt.ls.core 4 0 2020-07-08 14:20:02.679
!MESSAGE Error in calling delegate command handler
!STACK 1
org.eclipse.core.runtime.CoreException: Given URI does not belong to any Java project.
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getJavaProjectFromUri(ProjectCommand.java:257)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getProjectSettings(ProjectCommand.java:82)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:65)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:495)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
!SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2020-07-08 14:20:02.679
!MESSAGE Given URI does not belong to any Java project.

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.757
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.758
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.799
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:02.800
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:03.024
!MESSAGE >> workspace/executeCommand java.project.provideSemanticTokens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:03.026
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:03.132
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:05.981
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:05.983
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:08.236
!MESSAGE >> workspace/executeCommand vscode.java.isOnClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:08.768
!MESSAGE >> workspace/executeCommand vscode.java.updateDebugSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:08.786
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:10.705
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:10.716
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:10.904
!MESSAGE >> workspace/executeCommand vscode.java.resolveJavaExecutable

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:10.915
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:12.197
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:12.213
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:15.669
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:21.074
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:24.931
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:24.933
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:25.226
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:25.229
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:25.381
!MESSAGE >> workspace/executeCommand sts.java.addClasspathListener

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:25.848
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:25.849
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:28.867
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:29.382
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:29.397
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:31.080
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:31.088
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:32.302
!MESSAGE >> document/didClose

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:33.216
!MESSAGE >> shutdown

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:33.220
!MESSAGE >> exit

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:33.468
!MESSAGE Shutdown received... waking up main thread

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-08 14:20:33.491
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:`

**Comment by akaroml** [comment]
@testforstephen could you please take a look? It looks like a non-project file issue.

**Comment by testforstephen** [comment]
@dupinder When you uninstalled vscode-lombok, actually it wasn't really removed from Java language server. See the user settings `"java.jdt.ls.vmargs"`, and it still contains a part `-javaagent:"c:\Users\DupinderDhiman.vscode\extensions\gabrielbb.vscode-lombok-1.0.1\server\lombok.jar"`.  This is mentioned at https://github.com/redhat-developer/vscode-java/issues/743#issuecomment-446738302, you need manually remove "-javaagent" from `"java.jdt.ls.vmargs"` user setting to keep vscode-lombok fully cleaned up.

> I did it, Uninstall lombok and created one java file and boom

From the log you provided, the language server actually is up. Could you explain a little more what failure you got when you created one Java file?

**Comment by dupinder** [comment]
OKay I will try what @testforstephen is asking to do, and will update :) Thankyou
