### ISSUE TITLE
[error] command 'java.execute.workspaceCommand' not found: Error: command 'java.execute.workspaceCommand' not found

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode-java-pack#42]
I installed the Java pack. When i try to open a Java file, I have an error popup saying that a command is missing.
In Log (Window) there are several stacktraces (including one with the message mentioned):

```
[2018-10-08 10:44:19.209] [renderer1] [info] no standard startup: panel is active
[2018-10-08 10:44:27.930] [renderer1] [error] command 'java.open.output' already exists: Error: command 'java.open.output' already exists
	at e.registerCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:618)
	at Object.registerCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:799:950)
	at languageClient.onReady.then (C:\Users\Aurelien Pupier\.vscode\extensions\redhat.java-0.32.0\out\src\extension.js:187:39)
	at propagateAslWrapper (C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:502:23)
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:539:70
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at <anonymous>
[2018-10-08 10:50:42.773] [renderer1] [info] no standard startup: not just one text editor
[2018-10-08 10:50:49.911] [renderer1] [error] command 'java.open.output' already exists: Error: command 'java.open.output' already exists
	at e.registerCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:618)
	at Object.registerCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:799:950)
	at languageClient.onReady.then (C:\Users\Aurelien Pupier\.vscode\extensions\redhat.java-0.32.0\out\src\extension.js:187:39)
	at propagateAslWrapper (C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:502:23)
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:539:70
	at C:\Users\Aurelien Pupier\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at <anonymous>
[2018-10-08 10:57:37.949] [renderer1] [error] command 'java.execute.workspaceCommand' not found: Error: command 'java.execute.workspaceCommand' not found
    at t._tryExecuteCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:717)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:572
    at n.Class.derive._oncancel.then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161:366)
    at t.executeCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:546)
    at e.$executeCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3174:846)
    at e._doInvokeHandler (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3235:593)
    at e._invokeHandler (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3235:311)
    at e._receiveRequest (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3234:129)
    at e._receiveOneMessage (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3233:270)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3232:74
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at a (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:740)
    at Socket.n._socketDataListener (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:959)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[2018-10-08 10:57:39.351] [renderer1] [error] command 'java.execute.workspaceCommand' not found: Error: command 'java.execute.workspaceCommand' not found
    at t._tryExecuteCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:717)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:572
    at n.Class.derive._oncancel.then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161:366)
    at t.executeCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:546)
    at e.$executeCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3174:846)
    at e._doInvokeHandler (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3235:593)
    at e._invokeHandler (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3235:311)
    at e._receiveRequest (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3234:129)
    at e._receiveOneMessage (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3233:270)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3232:74
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at a (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:740)
    at Socket.n._socketDataListener (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:959)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by apupier** [comment]
the issue was coming from a duplicated name of command registered. I changed it in Apache Camel extension (naming was not great for this extension)

thought for later:
- would be nice to provide who has registered the "already registered command" to know which extensions are conflicting
- would be nice to have a convention for command name and having warnings when not following it to avoid conflict while developing

**Comment by delayk** [comment]
I had the same issue on windows before. I did not install any other plugins but only the java extension pack.
Here is the way I solved it.
Delete the "Code" folder under  AppData\Roaming, and restart the application.

**Comment by sochooligan** [comment]
Please install plugin {Lombok Annotations Support for VS Code}

**Comment by Arto358** [comment]
I just tested all your tips but it didn't work for me
I have: command 'java.execute.workspaceCommand' not found
and source: Debugger for java (extension)
if you can help me please
