### ISSUE TITLE
Error: Could not find or load main class QuickStart

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode-java-pack#488]
Issue Type: <b>Bug</b>

Launch fails the QuickStart example after following Java Getting Started. 

The console shows:
 /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:63466 -Dfile.encoding=UTF-8 -cp /var/folders/qd/1h500p390x1122wqbrl02cw00000gr/T/cp_a79kie5xw1i0heaqznlq6sjs4.jar ca.epbc.ui.QuickStart 

 $  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:63466 -Dfile.encoding=UTF-8 -cp /var/folders/qd/1h500p390x1122wqbrl02cw00000gr/T/cp_a79kie5xw1i0heaqznlq6sjs4.jar ca.epbc.ui.QuickStart Error: Could not find or load main class ca.epbc.ui.QuickStart

jar files are not getting created.
$ ls -l /var/folders/qd/1h500p390x1122wqbrl02cw00000gr/T/*jar
ls: /var/folders/qd/1h500p390x1122wqbrl02cw00000gr/T/*jar: No such file or directory
$ 

The QuickStart file structure is:
src/main/java/ca/epbc/ui/QuickStart.java

Extension version: 0.10.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|--crash-reporter-id 161e5da9-f592-4143-baa2-0a9d01a1bfab|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dfdumaresq** [comment]
!ENTRY org.eclipse.jdt.ls.core 4 2 2020-10-22 13:51:56.958
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:152)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:206)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:495)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

!ENTRY org.eclipse.jdt.ls.core 4 0 2020-10-22 13:51:56.958
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:152)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:206)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:495)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by testforstephen** [comment]
The cp_*.jar is a temp file, and will be deleted when the debugging ends. That's why you cannot ls it from terminal after debugging.

Could you share a sample project for us to reproduce?

**Comment by dfdumaresq** [comment]
I finally got this working. What I needed to do was sort out which JDK version was being used. 
1. set java.configuration.runtimes in settings as 
`  {
    "name": "JavaSE-14",
    "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home",
    "default": true
  }`
2. set JAVA_HOME and JDK_HOME (maybe not necessary) in env.
