### ISSUE TITLE
[Bug]when you go to the define of a class, you will get NPE error

### ISSUE THREAD

**Issue by rockxsj** [microsoft/vscode-java-pack#506]
**Environment:**

- VS Code Version: 1.51.1
- Extension Version:  v0.10.0
- JDK Type & Version: jdk-11.0.9+11

版本: 1.51.1 (user setup)
提交: e5a624b788d92b8d34d1392e4c4d9789406efe8f
日期: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Step to Reproduce:**
just click go to the define of any jdk buildin class.
**Expected Behavior:**
open the class file.
**Actual Behavior:**
``` log
java.io.FileNotFoundException: /java.base/java.time.chrono/ChronoZonedDateTime.class (No such file or directory)
-----------------------------------------------------------------------------------------

	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at de.fernflower.main.decompiler.ConsoleDecompiler.getBytecodeStream(Unknown Source)
	at cz.a(Unknown Source)
	at i.a(Unknown Source)
	at i.a(Unknown Source)
	at de.fernflower.main.decompiler.ConsoleDecompiler.addSpace(Unknown Source)

-----------------------------------------------------------------------------------------
	at de.fernflower.main.decompiler.ConsoleDecompiler.main(Unknown Source)

-----------------------------------------------------------------------------------------
java.lang.NullPointerException
-----------------------------------------------------------------------------------------

	at bW.a(Unknown Source)
	at bW.<init>(Unknown Source)
	at i.a(Unknown Source)
	at i.a(Unknown Source)
	at de.fernflower.main.decompiler.ConsoleDecompiler.addSpace(Unknown Source)
	at de.fernflower.main.decompiler.ConsoleDecompiler.main(Unknown Source)
-----------------------------------------------------------------------------------------
```
**Related Issues:**

**Comment by testforstephen** [comment]
> at de.fernflower.main.decompiler.ConsoleDecompiler.main(Unknown Source)

thanks for reporting the issue. I see the NPE is threw by the decompiler extension. Which Java decompiler extension do you install?

**Comment by rockxsj** [comment]
> decompiler

Thanks for reply! The decompiler extension is `dgileadi.java-decompiler`, and version is v0.0.2

**Comment by testforstephen** [comment]
this issue should be duplicated with https://github.com/dgileadi/vscode-java-decompiler/issues/8, i would suggest to move the issue to there for further discussion.

**Comment by akaroml** [comment]
@testforstephen is there a conclusion here?

**Comment by testforstephen** [comment]
This is the issue from the decomplier extension, the language features not work in the decompiled code at the moment. Need improve the decompiler extension to make it better integrated with the Java tooling.

**Comment by testforstephen** [comment]
@rockxsj As we know, the extension `cweijan.vscode-office` will cause this error, see https://github.com/redhat-developer/vscode-java/issues/1741#issuecomment-746128965.
