### ISSUE TITLE
The type X from the descriptor computed for the target context is not visible here

### ISSUE THREAD

**Issue by DougTea** [microsoft/vscode-java-pack#530]
**Environment:**

- VS Code Version: 1.52.1
- Extension Version: v0.12.1
- JDK Type & Version: openjdk-11
- OS Type & Version: linux

**Step to Reproduce:**
open a maven java project with vscode.The project comtains some lambda expression.
**Expected Behavior:**
build project without compile error
**Actual Behavior:**
Project is failed to build with all lambda expression come with an error:
The type [MyType] from the descriptor computed for the target context is not visible here.  
**Related Issues:** 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=478533

**Comment by akaroml** [comment]
Thanks for reaching out @MrTinyK 

Could you please provide a sample project to help us reproduce this issue?

**Comment by DougTea** [comment]
https://github.com/DougTea/test
link above is a sample project that can reproduce this issue.Line 16 in App.java come with a problem:The type HttpSecurity from the descriptor computed for the target context is not visible here.
@akaroml

**Comment by testforstephen** [comment]
@DougTea i tried the sample project in macOS, there are no compilation errors.

![image](https://user-images.githubusercontent.com/14052197/103502802-619d8300-4e8d-11eb-8ca6-f3c0513092ef.png)

Could you share the server logs?

**F1 -> Java: Open Java Language Server Log File**

**Comment by DougTea** [comment]
When I reopen this project,the problem I have seen before is gone.
After several trial，I found that if I change the lambda expression,the problem will go back.Specifically,rename "authorization".
![image](https://user-images.githubusercontent.com/16688151/103505995-aaa60500-4e96-11eb-979a-042579444c2e.png)

And the lsp log file got this error:

`!ENTRY org.eclipse.jdt.ls.core 1 0 2021-01-04 14:12:10.495
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 4 2 2021-01-04 14:12:10.500
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:154)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:205)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-01-04 14:12:10.504
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:154)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:205)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by testforstephen** [comment]
I can reproduce it too. This seems related with the generic type because your original configure parameter used a generic type <HttpSecurity>. Declare the parameter type explicitly in the lambda can fix the error. 

```java
    public static AuthorizeConfigurer predicate(){
        //lamda expression got problem:The type HttpSecurity from the descriptor computed for the target context is not visible here.  
        return (ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry authorization) -> authorization.anyRequest().permitAll();
    }
```
