### ISSUE TITLE
'java.execute.workspaceCommand' failed

### ISSUE THREAD

**Issue by kking124** [microsoft/vscode-java-pack#551]
I've been trying to get the java pack working in vscode version 1.53.0 for several days now.

To simplify things, I'm running a project that just outputs Hello World!

```java
package com.example;

/**
 * Hello world!
 *
 */
public class App 
{
    /** 
     * Output Hello World!
     */
    public static void main( String arg[] )
    {
        System.out.println( "Hello World!" );
    }
}
```

command line output is successful when run manually:
```
PS %USERPROFILE%\Code\projects\java\test\target\classes> .\java.exe com/example/App                          

Hello World!
```

but VSCode gives me a cryptic: `Running the contributed command: 'java.execute.workspaceCommand' failed.`

my launch.json is as follows:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "mainClass": "${file}"
        }
    ]
}
```

settings.json:
```json
{
    "java.configuration.updateBuildConfiguration": "automatic"
}
```

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>helloWorld</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>helloWorld</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.14</maven.compiler.source>
    <maven.compiler.target>1.14</maven.compiler.target>
    <maven.compiler.release>14</maven.compiler.release>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

I'm targeting: `AdoptOpenJDK jre-14.0.2-12-hotspot`

How would I find log information on this problem to continue to diagnose and correct? When I click on the `Learn More` button I'm taken to a bunch of unhelpful suggestions.

Edit:
the Log (Extension Host) indicates the following:

```
[2021-03-01 10:32:16.084] [exthost] [error] Error: com/sun/jdi/AbsentInformationException
	at %userprofile%\.vscode\extensions\redhat.java-0.75.0\dist\extension.js:1:76464
	at %userprofile%\.vscode\extensions\redhat.java-0.75.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (%userprofile%\.vscode\extensions\redhat.java-0.75.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:456:21) java.execute.workspaceCommand
```

so clearly I'm missing **SOMETHING** in the launch command or `.classpath` but the online docs indicate that I'm not.

I would also note that CodeLens does not detect my `main` method in `App`.

Current file structure
```
test\
  | -- .vscode\
  |     | -- launch.json
  |     | -- settings.json
  | -- helloWorld\
        | -- .settings\
        | -- src\main\java\com\example\
        |      | -- App.java
        | -- target\
        | -- .classpath
        | -- .project
        | -- pom.xml
```

Language Support for Java output:
```
[Error - 2:12:20 PM] Mar 1, 2021, 2:12:20 PM Error in calling delegate command handler
com/sun/jdi/AbsentInformationException
java.lang.NoClassDefFoundError: com/sun/jdi/AbsentInformationException
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.getJavaProjectFromType(ResolveClasspathsHandler.java:109)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.searchClassInProjectClasspaths(ResolveMainClassHandler.java:206)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateMainClass(ResolveMainClassHandler.java:193)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfigCore(ResolveMainClassHandler.java:175)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfig(ResolveMainClassHandler.java:70)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:72)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.AbsentInformationException cannot be found by com.microsoft.java.debug.plugin_0.30.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
```

**Comment by peterxucn** [comment]
I met the same problem. And I changed the `java.home` in settings.json from:  

```json
{
  "java.home": "/path/to/jre15"
}
```

to:  

```json
{
  "java.home": "/path/to/jdk15"
}
```

After that, it's solved.

My development environment is:  

```yaml
OS: Ubuntu 18.04
VSCode: 1.54.1
VSCode Extension - Language support for Java: 0.76.0
VSCode Extension - Debugger for Java: 0.31.0
```

**Comment by kking124** [comment]
Thanks!

Worked on the following environment as well:

```
OS: Windows 10 Pro 20H2 (build 19042.746)
VSCode: 1.53.2
VSCode Extension - Language support for Java: 0.76.0
VSCode Extension - Debugger for Java: 0.31.0
```
