### ISSUE TITLE
java: setting starThreshold=0 breaks java intellisense

### ISSUE THREAD

**Issue by rrizun** [microsoft/vscode-java-pack#590]
Issue Type: <b>Bug</b>

in settings.json, setting either of these values to "0" breaks java intellisense

"java.sources.organizeImports.starThreshold": 0,
"java.sources.organizeImports.staticStarThreshold": 0,

that is, e.g., type "this." and observe that the java intellisense does not appear

as long as neither value is zero (0), then java intellisense appears, e.g., typing "this." shows the java intellisense

observed on two (2) different macs (both big sur)

Extension version: 0.13.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.18GB free)|
|Process Argv|--crash-reporter-id a358c2e5-7326-4e2d-9621-94d384a0d43e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by jdneo** [comment]
Observed an error at log file:

```
!MESSAGE Threshold must be positive.
!STACK 0
java.lang.IllegalArgumentException: Threshold must be positive.
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.setOnDemandImportThreshold(ImportRewrite.java:487)
	at org.eclipse.jdt.ls.core.internal.contentassist.TypeProposalUtils.createImportRewrite(TypeProposalUtils.java:168)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:123)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:118)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.toCompletionItem(CompletionProposalRequestor.java:269)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:207)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:154)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:520)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
