### ISSUE TITLE
Project Manager: Error in calling delegate command handler

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#957]
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getInstallLocation()" because the return value of "org.eclipse.jdt.launching.JavaRuntime.getVMInstall(org.eclipse.jdt.core.IJavaProject)" is null
	at com.microsoft.jdtls.ext.core.ExtUtils.getContainerURI(ExtUtils.java:115)
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForClasspathEntry(PackageNode.java:261)
	at com.microsoft.jdtls.ext.core.PackageCommand.lambda$7(PackageCommand.java:264)
	at $3$1.accept(Unknown Source)
	at $2$1.accept(Unknown Source)
	at $ArraySpliterator.forEachRemaining(Unknown Source)
	at (Unknown Source)
	at (Unknown Source)
	at $ReduceOp.evaluateSequential(Unknown Source)
	at (Unknown Source)
	at (Unknown Source)
	at com.microsoft.jdtls.ext.core.PackageCommand.getContainers(PackageCommand.java:266)
	at com.microsoft.jdtls.ext.core.PackageCommand.getChildren(PackageCommand.java:107)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:31)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
```

**Comment by nickzhums** [comment]
a
