### ISSUE TITLE
Failed to save JDT index

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#960]
Different call stacks below:

```
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:983)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readCategoryTable(DiskIndex.java:689)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeCategory(DiskIndex.java:485)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeCategories(DiskIndex.java:477)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:579)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:230)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1143)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1201)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:819)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:422)
```

```
java.io.FileNotFoundException: xxxxxxx yyyyyyy (No such file or directory)
	at (Native Method)
	at (Unknown Source)
	at <init>(Unknown Source)
	at org.eclipse.jdt.internal.core.index.FileIndexLocation.getInputStream(FileIndexLocation.java:81)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:630)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:532)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:230)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1143)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1201)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:819)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:422)
```

```
java.io.IOException: Stream was closed for index location "xxxxxxx"
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:751)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:640)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:532)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:230)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1143)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1201)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:819)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:422)
```

**Comment by rgrunber** [comment]
Looks similar to https://github.com/redhat-developer/vscode-java/issues/2232 , except that also shows an OOM occurring.

**Comment by Eskibear** [comment]
closing this as stale
